name: Good Story
favicon: null
layout_spectrum: 0.2905325267929584
typography_spectrum: 0.9001911790110171
title: Business Support for Bright Young Entrepreneurs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1ea39a'
    - '#1d1f21'
    - '#ef714c'
    - '#ffffff'
    - '#f6e40d'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
